# theme  = "lackluster"

[editor]
line-number = "relative"
cursorline =  true
true-color = true
popup-border = "none"
color-modes =  true
completion-timeout  =  5
preview-completion-insert = false
text-width = 100
rulers = [100]
gutters = [  "diff", "line-numbers", "spacer", "diagnostics",  "spacer"]
end-of-line-diagnostics = "warning"

[editor.auto-save]
focus-lost = false

[editor.statusline]
mode.normal = "normal"
mode.insert = "insert"
mode.select = "visual"
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[editor.lsp]
display-progress-messages = true

[keys.normal]
q = ":wa"
Q = ":qa"

[keys.insert]
C-l = "goto_next_tabstop"
C-k = "goto_prev_tabstop"
