[font]
size = 14

[font.offset]
y = -3

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# family = "JetBrainsMono Nerd Font"
# style = "Light"

# screenshot
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

# retro hacker 
# family = "JetBrainsMono Nerd Font"
# style = "Regular"

[colors.primary]
background = '#101010'
# background = '#000000'
# background = '#202022'

[window]
# opacity = 0.95

[window.padding]
x = 10
y = 10

# Normal colors
[colors.normal]
black = '#080808'
red = '#D70000'
green = '#789978'
yellow = '#ffAA88'
blue = '#7788AA'
magenta = '#D7007D'
cyan = '#708090'
white = '#deeeed'

[[keyboard.bindings]]
key = "F"
mods = "Command"
action = "ToggleSimpleFullscreen"
