"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Duncan Marsh"
email = "slugbyte@slugbyte.com"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/slugbyte.pub"

[aliases]
e = ["edit"]
s = ["status"]
d = ["desc"]
n = ["new"]
x = ["abandon"]
ll = ["log", "-r", "..@"]

[ui]
pager = ":builtin"
conflict-marker-style = "snapshot"
default-command = "log"

[git]
sign-on-push = true

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
